export const CREATE_FLOWER = "CREATE_FLOWER";
export const LOAD_FLOWERS_SUCCESS = "LOAD_FLOWERS_SUCCESS";
export const UPDATE_CART_QTY = "UPDATE_CART_QTY";
export const UPDATE_CART = "UPDATE_CART";
export const DECREMENT_CART_QTY = "DECREMENT_CART_QTY";
